"""Followers model

Revision ID: 2e390f2d724e
Revises: 7850fa9c4284
Create Date: 2025-08-05 14:25:58.136803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e390f2d724e'
down_revision = '7850fa9c4284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('followers_follower_fkey'), type_='foreignkey')
        batch_op.drop_column('follower')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follower', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('followers_follower_fkey'), 'users', ['follower'], ['id'])

    # ### end Alembic commands ###
