"""campos picture url y bgimage url agregados al modelo de User

Revision ID: 98f40bac83af
Revises: 48d175fc025b
Create Date: 2025-07-16 11:58:54.879775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f40bac83af'
down_revision = '48d175fc025b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bgimage_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bgimage_url')
        batch_op.drop_column('picture_url')

    # ### end Alembic commands ###
